version: "3.9"
services:
  spring-api-image:
    container_name: spring-api-container
    image: spring-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7056:7056"
    networks:
      - spring-network
    depends_on:
      - db-spring
  db-spring:
    image: mysql
    container_name: mymysql4
    environment:
      MYSQL_ROOT_PASSWORD: sql123
      MYSQL_DATABASE: dockerDB
      MYSQL_USER: springdb
      MYSQL_PASSWORD: sql123
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume:
